# Generated by Django 2.0.13 on 2019-11-16 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_dislikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
