# Generated by Django 2.0.13 on 2019-12-08 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20191120_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files_upload',
            name='post',
        ),
        migrations.DeleteModel(
            name='Files_Upload',
        ),
    ]
