# Generated by Django 2.0.13 on 2019-12-14 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_comment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
    ]
